---
-
  become: true
  hosts: all
  tasks:
    -
      name: "install the latest version of Apache"
      yum:
        name: httpd
        state: latest
      tags:
        - install
    -
      name: starting service
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - start
    -
      name: stop service
      service:
           name: httpd
           state: stopped
      tags:
         - stop


