---
- hosts: all
  become: yes
  gather_facts: no  

  tasks:
    - name: add several users
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      with_items:
        - { name: 'ansible-user-1', groups: 'tomcat' }
        - { name: 'ansible-user-2', groups: 'ec2-user' }


