---
- hosts: all
  become: yes
  gather_facts: no  

  tasks:
    - name: add several users
      user:
        name: "{{ item }}"
        state: absent
        groups: "root"
      with_items:
        - nagi
        - bala

