---
-
  become: true
  hosts: all
  tasks:
    - name: Download package from nexus
      get_url: url=http://34.215.252.242:8081/nexus/service/local/artifact/maven/redirect?g=in.mphasis&a=DevOpsDemoProject&v=LATEST&r=snapshots&p=war dest="/tmp/myweb.war" force=yes
